language: java
jdk:
  - oraclejdk8
  - openjdk11

script:
  - ./gradlew check jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      - secure: "aPLtOmCd024UPeUnQO1yHLYAqiuwEJw4EDiJ7lbxLEjBBq4m0LHNvA39z1EDIntumN4BfDcA1uMsxsZiNCqOU1Xan6LsDYdinyYYA9XOSr3Tl2jkAb8Byaehpsl4QNjA0J/0SRKaTiIPzgX9zWYsh+ejuwG72bknFR9bbQ9Azb+o3iiAyQkhi2rs/fCGgrRlM9CRi/LlKrs3Z16zosrz6j06ndPUA4cNBbV5Wpzxa/RPGPU8Av0yN7Eehku6TDaArf7Dvt9tKdmctSEjvhwaFvLWFGb4NMXZamPZcTQMIKQzNf73m8BNRpzm/PZmGQ+UfGfwSE80u1aY4aDoKPMhkFKQy85uhUZN9PQep6/+jsKm1lO7nzZj4O8lPzb1ijVJrSDuaICgW26O/4JWaWv2pud7aU4LwC4eXXMS0vxKxJVtZ1a+I7LVppzmcJI84Pk11yGQv74mquzaHVqWSv9fXrbyL0VoHK0yzVVVGchxLP1s6YTkAZu3GTH0UINYafMlhKvGdFTCSzA4VHPELRXN9EepvteQFCOEr5ZiT/VgE2QFmZ9iTJ69VuEPgeapc3M8THKlCqqu89K6iR+sm4tFftMI8Kp1f1xfHQ5lvvuYwDftbPUSJ/hTgWiLldKkP5T+YuDTfD8sBer/l0lf+PlzUL1mY1tKz74DQR3EW8QgyNI="

