language: java
jobs:
  include:
    - dist: xenial
      jdk: oraclejdk8
    - dist: focal
      jdk: openjdk11

script:
  - ./gradlew check jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    - secure: "KewjxllsfAovdka9jrZPDIwKcob2QXRLyVLiA7p3H2H2oE4/Lr6EJwxzDY6ICDHgIct16L6CqJK4whlpqDLbRg7FftG5Dn9oUozG33yskECA8nCK34tGB2jS8govIgs8RHuVnnHpw0/hOm2pTYuHdmunnY/o59KASY1+1fNESxS7Xmbk+bTs7olU4LQ5f3TX8hVFgF4V8gRnzhVtdw/zB87/McY8FBibPaQvGrJWWhi+qvR+VzmgXs/MIVrtfHRIyci2V1Ab51ddvX8VhEr+HFOlF73nE8kjsvR+ohzojK5Y77MqaCP/2qdg8lPP4UvS3SAHgsxa93f2nEboDiKgpq5f2F/Hw1O/8AP+kzkAMoFAuExTKCq0AY2Ig1/pdPYp9dFCTfArM6mDXiF/J++JpXtTlioxxk589QoTITWs3Ynln8pFIT1qLbsVNUZXTDcFznjmrunX4GOi5WB4f04kN+wjfqWE/brQV0K3Qq03wLb6TK7co8jvlkGeTKS6zu5oYG+cF6rIlEclfNKUDWGRDKXCOPqgxkt6at8dbRG9nkksfx7ftpiTRteA5/6o+YyPaRiq5qjxAVlHtkRFbADfIKJ5kgrEa+w5FBC+bz+4Ctw31hYLM82osQrcRMsRckjOiUQcBnGh8ONzKrgu3kfuwfngAp2qsaP/qX65R+LMy7k="
